User.all
Truck.destroy_all
Location.destroy_all
# Review.destroy_all
# Favorite.destroy_all
Schedule.destroy_all
Item.destroy_all
Neighborhood.destroy_all
Category.destroy_all


neighborhood_1 = Neighborhood.create(name: "Midtown")
neighborhood_2 = Neighborhood.create(name: "Jamaica")
neighborhood_3 = Neighborhood.create(name: "Astoria")

loc1 = Location.create(street_address: "300 West 55th Street", city: "New York", state: "NY", zip: "10019", neighborhood_id: neighborhood_1.id)
loc2 = Location.create(street_address: "3105 Astoria Blvd S", city: "Astoria", state: "NY", zip: "11101", neighborhood_id: neighborhood_3.id)
loc3 = Location.create(street_address: "11811 84th Avenue", city: "Kew Gardens", state: "NY", zip: "11415", neighborhood_id: neighborhood_2.id)
loc4 = Location.create(street_address: "Columbus Circle", city: "New York", state: "NY", zip: "10019", neighborhood_id: neighborhood_1.id)
loc5 = Location.create(street_address: "Bryant Park", city: "New York", state: "NY", zip: "10018", neighborhood_id: neighborhood_1.id)

loc6 = Location.create(street_address: "102 W 35th St", city: "New York", state: "NY", zip: "10001", neighborhood_id: neighborhood_1.id)
loc7 = Location.create(street_address: "655 W 34th St", city: "New York", state: "NY", zip: "110001", neighborhood_id: neighborhood_1.id)
loc8 = Location.create(street_address: "390 7th Ave", city: "New York", state: "NY", zip: "10001", neighborhood_id: neighborhood_1.id)
loc9 = Location.create(street_address: "24 Broadway", city: "New York", state: "NY", zip: "10004", neighborhood_id: neighborhood_1.id)
loc10 = Location.create(street_address: "142 John Street", city: "New York", state: "NY", zip: "10038", neighborhood_id: neighborhood_1.id)
loc11 = Location.create(street_address: "95 Wall Street", city: "New York", state: "NY", zip: "10005", neighborhood_id: neighborhood_1.id)
loc12 = Location.create(street_address: "124 University Pl", city: "New York", state: "NY", zip: "10003", neighborhood_id: neighborhood_1.id)
loc13 = Location.create(street_address: "Bryant Park", city: "New York", state: "NY", zip: "10018", neighborhood_id: neighborhood_1.id)
loc14 = Location.create(street_address: "162 W 56th St", city: "New York", state: "NY", zip: "10019", neighborhood_id: neighborhood_1.id)
loc15 = Location.create(street_address: "23 3rd Ave", city: "New York", state: "NY", zip: "10003", neighborhood_id: neighborhood_1.id)
loc16 = Location.create(street_address: "1270 Broadway", city: "New York", state: "NY", zip: "10001", neighborhood_id: neighborhood_1.id)
loc17 = Location.create(street_address: "152 W 49th St", city: "New York", state: "NY", zip: "10019", neighborhood_id: neighborhood_1.id)
loc18 = Location.create(street_address: "723 3rd Ave", city: "New York", state: "NY", zip: "10017", neighborhood_id: neighborhood_1.id)
loc19 = Location.create(street_address: "132 Wooster St", city: "New York", state: "NY", zip: "10012", neighborhood_id: neighborhood_1.id)
loc20 = Location.create(street_address: "41 E 51st St", city: "New York", state: "NY", zip: "10022", neighborhood_id: neighborhood_1.id)
loc21 = Location.create(street_address: "56 Jay Street", city: "Brooklyn", state: "NY", zip: "11201", neighborhood_id: neighborhood_1.id)
loc22 = Location.create(street_address: "madison square eats", city: "New York", state: "NY", zip: "10010", neighborhood_id: neighborhood_1.id)
loc23 = Location.create(street_address: "160 Bay Street", city: "Brooklyn", state: "NY", zip: "11231", neighborhood_id: neighborhood_1.id)
loc24 = Location.create(street_address: "211 Prospect Park West", city: "Brooklyn", state: "NY", zip: "11215", neighborhood_id: neighborhood_1.id)
loc25 = Location.create(street_address: "185 Water Street", city: "Brooklyn", state: "NY", zip: "11201", neighborhood_id: neighborhood_1.id)
loc26 = Location.create(street_address: "40 Wall St", city: "New York", state: "NY", zip: "10005", neighborhood_id: neighborhood_1.id)
loc27 = Location.create(street_address: "60 2nd Avenue", city: "New York", state: "NY", zip: "10003", neighborhood_id: neighborhood_1.id)
loc28 = Location.create(street_address: "320 Park Avenue", city: "New York", state: "NY", zip: "10022", neighborhood_id: neighborhood_1.id)
loc29 = Location.create(street_address: "45 Rockefeller Plaza", city: "New York", state: "NY", zip: "10111", neighborhood_id: neighborhood_1.id)


priyam = User.create(f_name: "Priyam", l_name: "Sarma", email: "priyam.sarma@gmail.com", username: "psarma89", password: "priyam", password_confirmation: "priyam", location_id: loc1.id)
rochel = User.create(f_name: "Rochel", l_name: "Levi", email: "rochel.levi@gmail.com", username: "rlevi96", password: "rochel", password_confirmation: "rochel", location_id: loc2.id)
mark = User.create(f_name: "Mark", l_name: "White", email: "mark@gmail.com", username: "mwhite", password: "markwhite", password_confirmation: "markwhite", location_id: loc2.id)
jazmin = User.create(f_name: "Jazmin", l_name: "Sanchez", email: "jsanchez@gmail.com", username: "jslovespuppies", password: "jazmin", password_confirmation: "jazmin", location_id: loc2.id)
mike = User.create(f_name: "Mike", l_name: "Samet", email: "msamet@gmail.com", username: "mickey", password: "mikesamet", password_confirmation: "mikesamet", location_id: loc2.id)
frankie = User.create(f_name: "Frankie", l_name: "Chen", email: "fchen@gmail.com", username: "frankc", password: "frankie", password_confirmation: "frankie", location_id: loc2.id)
craig = User.create(f_name: "Craig", l_name: "Chu", email: "craigchu@gmail.com", username: "craigndiane", password: "craigchu", password_confirmation: "craigchu", location_id: loc2.id)
greg = User.create(f_name: "Greg", l_name: "Zelikovsky", email: "gzelikov@gmail.com", username: "zelikov", password: "gregory", password_confirmation: "gregory", location_id: loc2.id)
martin = User.create(f_name: "Martin", l_name: "Weiss", email: "weiss.marty@gmail.com", username: "marty", password: "martin", password_confirmation: "martin", location_id: loc2.id)


cat1 = Category.create(name: "Halal")
cat2 = Category.create(name: "Jamaican")
cat3 = Category.create(name: "Mexican")
cat4 = Category.create(name: "Juice")
cat5 = Category.create(name: "Waffles")
cat6 = Category.create(name: "Sandwiches")
cat7 = Category.create(name: "Vegan")
cat8 = Category.create(name: "Lebanese")
cat9 = Category.create(name: "Pizza")
cat10 = Category.create(name: "Seafood")
cat11 = Category.create(name: "Korean")
cat12 = Category.create(name: "Greek")
cat13 = Category.create(name: "Asian")
cat14 = Category.create(name: "Burgers")
cat15 = Category.create(name: "German")
cat16 = Category.create(name: "Salvadoran")
cat17 = Category.create(name: "Dessert")
cat18 = Category.create(name: "Vietnamese")
cat19 = Category.create(name: "Polish")
cat20 = Category.create(name: "Cheesesteaks")


truck1 = Truck.create(name: "The Halal Guys", category_id: cat1.id, location_id: loc1.id, img_url: "http://newyork.seriouseats.com/images/2012/10/20121002-halal-taste-test-famous-halal-52nd-cart.jpg")
truck2 = Truck.create(name: "Jus by Julie", category_id: cat4.id, location_id: loc4.id, img_url: "https://yeahthatskosher.com/wp-content/uploads/2016/11/JUS-by-Julie-kosher-food-juice-truck-nyc.png")
truck3 = Truck.create(name: "Wafels & Dinges", category_id: cat5.id, location_id: loc6.id, description: "Gorilla Cheese NYC is leading the NYC food truck revolution, taking comfort food and home cooking to a new level. We use only use fresh baked bread delivered from our local bakeries, and a wide variety of delicious cheeses. But what makes our sandwiches extra special is that they're always made with lots of love." , img_url: 'http://cravedujour.com/wp-content/uploads/2014/05/wafelsanddinges.jpg')
truck4 = Truck.create(name: "Gorilla Cheese NYC", category_id: cat6.id, location_id: loc7.id, description: "Gorilla Cheese NYC is leading the NYC food truck revolution, taking comfort food and home cooking to a new level. We use only use fresh baked bread delivered from our local bakeries, and a wide variety of delicious cheeses. But what makes our sandwiches extra special is that they're always made with lots of love.", img_url: 'http://1.bp.blogspot.com/-DA-JFs6ZEUs/UZ7ETjhPDtI/AAAAAAAAZQU/aM1TURU58Wc/s1600/IMG_2371.JPG')
truck5 = Truck.create(name: "The Cinnamon Snail", category_id: cat7.id, location_id: loc8.id, description: "The Vendy Award-winning and ever-so-whimsical Cinnamon Snail trucks have been changing how meat-eaters of NYC & New Jersey see vegan cuisine, with its unbelievably scrumptious selection of sandwiches, burgers, pastries, and more...all organic, all vegan, all insanely tasty. Chef and owner Adam Sobel is a man on a mission to evolve how the world eats; letting go of foods that cause cruelty to animals and damage to our planet, without sacrificing any flavor, one amazing meal from The Cinnamon Snail at a time.", img_url: 'https://roaminghunger.com/img/trucks/original/4de34df0-727c-4f45-a4d5-7ea746204482.jpg' )
truck6 = Truck.create(name: "GoGo Grill", category_id: cat6.id, location_id: loc9.id, description: "GoGo Grill is a cart in Bowling Green serving up tasty sandwiches and salads. Check out the meat and vegetarian english muffin sandwiches, the falafel on naan wrap, or the kale salad! And don't miss out on the daily specials." , img_url: 'https://roaminghunger.com/img/trucks/original/54342595-5f08-4bcc-bce6-394146204482.jpg')
truck7 = Truck.create(name: "Toum NYC", category_id: cat8.id, location_id: loc10.id, description: "Toum is the Lebanese word for garlic, and we serve up authentic Lebanese cuisine with a side of Toum dip on our food truck! Try the falafel, shawarma, kababs, and more!", img_url: 'https://roaminghunger.com/img/trucks/original/57daf112-567c-4f97-8527-059646204482.jpg' )
truck8 = Truck.create(name: "Jiannetto's Pizza", category_id: cat9.id, location_id: loc11.id, description: "Jiannetto’s Pizza & Catering has served as a staple in the NYC street food tradition since back in 1998, when the first iconic truck appeared on Wall Street. ",img_url: 'https://roaminghunger.com/img/trucks/original/4e4d5bb3-03c8-46da-9125-53a446204482.jpg')
truck9 = Truck.create(name: "Luke's Lobster", category_id: cat10.id, location_id: loc12.id, description: "Luke's Lobster is New York City's freshest, most affordable lobster roll -- straight from the docks of Maine.", img_url: 'https://roaminghunger.com/img/trucks/original/5578c454-b7c8-40da-bdc7-2a1d46204482.jpg' )
truck10 = Truck.create(name: "Kimchi Taco", category_id: cat11.id, location_id: loc13.id, description: "Kimchi Taco was born out of founders Phillip Lee and Chef Youngsun Lee's desire to share their love for Korean food with the world. 'Having had the opportunity to experience different types of cuisine while traveling and living in NYC, I realized the elements of Korean flavor and taste could stand up to any of the popular cuisines such as Italian, French or Japanese, says Phillip'. Their challenge was to figure out how to make Korean food accessible and memorable in ways that the general public could truly appreciate its unique and bold flavors.",  img_url: 'https://roaminghunger.com/img/trucks/original/4e3dc73b-7080-493a-991f-70b446204482.jpg' )
truck11 = Truck.create(name: "Souvlaki Grill", category_id: cat12.id, location_id: loc14.id, description: "Since 2010, Souvlaki GR has served New York with authentic Greek food, from family recipes passed down over generations. Now, they're taking tradition to the streets, crafting a menu of award-winning fare. After all, winning the New York Food and Wine Festival's People's Choice Award is no small feat. Along with two Vendys. Prepare yourself for big time flavor.",   img_url: 'https://roaminghunger.com/img/trucks/original/5924bc5e-10d4-4e7a-9601-422b46204482.jpg')
truck12 = Truck.create(name: "Korilla BBQ", category_id: cat11.id, location_id: loc15.id, description: "Introducing Korilla BBQ, the fiercest eats you'll find on the streets of the concrete jungle. What is a Korilla, you ask? It is nothing less than a Korean grillmasta serving up a complex combination of classic Korean recipes nestled within burritos or rice bowls like you've never had before." ,   img_url: 'https://roaminghunger.com/img/trucks/original/57993acc-f5e4-48cc-8d49-443046204482.png')
truck13 = Truck.create(name: "Coney Shack", category_id: cat13.id, location_id: loc16.id, description: "Fusion street cuisine that's perfect for any occasion is pulling up to a curb near you! This amazing food truck is serving up specialty tacos, burritos, quesadillas, and hot dogs, all with a fantastic Asian twist. This award winning food truck is bringing you all the flavor and quality food you could ever desire, today!",   img_url: 'https://roaminghunger.com/img/trucks/original/562014a7-7a0c-4444-a185-15e046204482.jpg')
truck14 = Truck.create(name: "Frites N Meats", category_id: cat14.id, location_id: loc17.id, description: "We know what it means to bite into a juicy, perfectly cooked Burger. We know you know it too. It's heaven! What we didn't know or understand was why it was so hard to get it. Not why it was hard to get a fancy pants Burger for $15+. That you can get anywhere. But why was it so hard to get that same fancy pants Burger at half that price or less. We looked, we looked and we looked some more, but it just wasn't there. So we decided to do it ourselves.",   img_url: 'https://roaminghunger.com/img/trucks/original/4dd0c735-c3d8-453f-870c-69cc46204482.jpeg')
truck15 = Truck.create(name: "Schnitzel and Things", category_id: cat15.id, location_id: loc18.id, description: "Schnitzel & Things is serving up incredibly tasty, authentic schnitzel; a hand pounded, lightly breaded thin cutlet (of chicken, pork, cod, or eggplant) fried to golden perfection, and served alongside a lemon wedge and and savory Austrian potato salad. And with all this deliciousness made fresh to order, it’s no wonder why New Yorkers are just loving this truck.",   img_url: 'https://roaminghunger.com/img/trucks/original/57d99656-3eb4-4e10-85cf-7eda46204482.jpg')
truck16 = Truck.create(name: "Calexico Cart", category_id: cat3.id, location_id: loc19.id, description: "Calexico Cart - Carne Asada street food cart in NYC. Check out the burritos and bowls, tacos, rolled quesadillas, and more!",   img_url: 'http://farm5.static.flickr.com/4126/4833118017_2e3be5c471.jpg')
truck17 = Truck.create(name: "El Toro Rojo Truck", category_id: cat3.id, location_id: loc20.id, description: "New York City may be known as the capital of several cuisines, but Mexican's never been amongst its strongest assets, 'til now. El Toro Rojo aims to blast authentic Oaxacan flavor through the streets of NYC, and by the crowds' reactions, their aim's been perfect.",   img_url: 'https://roaminghunger.com/img/trucks/original/596d3f39-5450-4f62-aace-112146204482.jpg')
truck18 = Truck.create(name: "Los Viajeros Food Truck", category_id: cat3.id, location_id: loc21.id, img_url: 'https://roaminghunger.com/img/trucks/original/57db028d-ec78-4466-87a8-55d246204482.jpg')
truck19 = Truck.create(name: "Asia Dog", category_id: cat13.id, location_id: loc20.id, img_url: 'https://roaminghunger.com/img/trucks/original/4e7a388b-ac48-4f39-a44b-552746204482.jpg')
truck20 = Truck.create(name: "El Olomega", category_id: cat16.id, location_id: loc23.id, img_url:'https://roaminghunger.com/img/trucks/original/570818ae-865c-4ee2-908d-118346204482.jpg' )
truck21 = Truck.create(name: "DUB Pies", category_id: cat17.id, location_id: loc24.id, img_url: 'https://roaminghunger.com/img/trucks/original/57db16f4-b7a4-4875-9e60-6e6446204482.jpg')
truck22 = Truck.create(name: "Sweet Chili", category_id: cat18.id, location_id: loc25.id, img_url: 'https://s3.amazonaws.com/iftbucket/2013/05/18145731/NY-truck-right-final.jpg' )
truck23 = Truck.create(name: "Neopolitan Express", category_id: cat9.id, location_id: loc26.id, img_url: 'https://roaminghunger.com/img/trucks/original/51546387-75d0-4f23-abca-025646204482.png' )
truck24 = Truck.create(name: "Old Traditional Polish Cuisine", category_id: cat19.id, location_id: loc27.id, img_url: 'https://roaminghunger.com/img/trucks/original/515f5fff-4e30-446f-881c-410446204482.jpg')
truck25 = Truck.create(name: "Phil's Steaks", category_id: cat20.id, location_id: loc28.id, img_url: 'https://roaminghunger.com/img/trucks/original/4f21cc4d-d440-4800-be03-3f3346204482.jpg' )
truck26 = Truck.create(name: "Gary's Steaks", category_id: cat20.id, location_id: loc29.id, img_url: 'https://roaminghunger.com/img/trucks/original/597b92bf-5b9c-4845-b005-290046204482.jpg' )
# truck27 = Truck.create(name: , category_id: cat3.id, location_id: loc20.id, img_url: )
# truck28 = Truck.create(name: , category_id: cat3.id, location_id: loc20.id, img_url: )
# truck29 = Truck.create(name: , category_id: cat3.id, location_id: loc20.id, img_url: )
# truck30 = Truck.create(name: , category_id: cat3.id, location_id: loc20.id, img_url: )
# truck31 = Truck.create(name: , category_id: cat3.id, location_id: loc20.id, img_url: )
# truck32 = Truck.create(name: , category_id: cat3.id, location_id: loc20.id, img_url: )
# truck33 = Truck.create(name: , category_id: cat3.id, location_id: loc20.id, img_url: )
# truck34 = Truck.create(name: , category_id: cat3.id, location_id: loc20.id, img_url: )
#

Favorite.create(truck_id: truck2.id, user_id: mike.id )
Favorite.create(truck_id: truck6.id, user_id: mike.id )
Favorite.create(truck_id: truck7.id, user_id: mike.id )
Favorite.create(truck_id: truck8.id, user_id: mike.id )
Favorite.create(truck_id: truck9.id, user_id: mike.id )
Favorite.create(truck_id: truck2.id, user_id: frankie.id )
Favorite.create(truck_id: truck10.id, user_id: frankie.id )
Favorite.create(truck_id: truck2.id, user_id: priyam.id )
Favorite.create(truck_id: truck11.id, user_id: priyam.id )
Favorite.create(truck_id: truck12.id, user_id: priyam.id )
Favorite.create(truck_id: truck13.id, user_id: rochel.id )
Favorite.create(truck_id: truck14.id, user_id: rochel.id )
Favorite.create(truck_id: truck2.id, user_id: rochel.id )

review1 = Review.create(title: "Not Great",  rating: 2, truck_id: truck2.id , user_id: mike.id, content: "Overpriced, and underwhelming. Juices are ill conceived and watered down with cheaper ingredients like rice milk (and less veg)muffins (though 100 calories) are so bland and flavorless. I make 100 cal yummies too, mine just don't taste like cardboard.")
review2 = Review.create(title: "My Favorite",  rating: 5, truck_id: truck2.id , user_id: jazmin.id, content:"Choco-nana is amazing! This place has very quick service and always serves me with a smile. Will always return!")
review3 = Review.create(title: "Dangerously Good",  rating: 5, truck_id: truck3.id, user_id: rochel.id, content: "Wow. These are  bit pricey but they are worth every penny! These things are delicious and I have to try not to eat too many of them! I took a friend here and he is now hooked too.")
review4 = Review.create(title: "Love This Place",  rating: 5, truck_id: truck3.id, user_id: jazmin.id, content: "Very yummy and nice to look at. If you have a sweet tooth, these waffles are a must! I do not usually gravitate towards sweet foods, however, this was definitely very delicious and I would definitely go again")
review5 = Review.create(title: "Best Breakfast!",  rating: 5, truck_id: truck3.id, user_id: craig.id, content:"I was hurrying to work the other day and I didn't have a chance to eat my lunch. Some tempting and sweet smell was around the waffle cart, so I just couldn't pass it without trying! I ordered simple waffle with Nutella, nothing special, but it was suuuper delicious. For less then 10$ you can get full and have a wonderful mood, because your endorphins will dance salsa after this. P.S Take a lot of napkins.")
review6 = Review.create(title: "meh",  rating: 3, truck_id: truck4.id, user_id: mark.id , content: "It's hard to justify spending money on grilled cheese when you can make the same thing at home with two slices of bread, 3 pieces of kraft cheese, and a stick of butter. Gorilla cheese doesn't add too much to that equation - if you want to spend even more they'll throw a few pieces of cold bacon into the mix, but overall it won't cure the nostalgia you've been feeling for grilled cheese.")
review7 = Review.create(title: "Nothing Special",  rating: 3, truck_id: truck4.id, user_id: frankie.id , content: "Gorilla Cheese was conveniently placed and it is located at a nice place to stop at, but at my experience it took a while to get my grilled cheese, and frankly it wasn't very good. The tater tots were hot and delicious, but the grilled cheese was not good at all. It was overpriced for a not so good sandwich.")
review8 = Review.create(title: "Food Was Cold",  rating: 1, truck_id: truck4.id, user_id: rochel.id, content: "The food was cold when we got it.  I think the issue may have been that they were handing out orders in order even if the person had a huge order.  It took almost 1 hour to get our food from the time we started ordering.  They should, in the future, make people with larger orders wait longer so that the people who only ordered one sandwich don't have to wait as long.  Also they had the guy serving the food also handing out the food which made the orders back up.  Thus, my tester tots were cold.  I ordered the chicken parm and it was cold and the marinara made the sandwich taste mushy.  Perhaps they should stick to just grilled cheeses so that the line moves faster.  Also, the portion of tater tots was not worth the extra cost.")
review9= Review.create(title: "Awesome!",  rating: 4, truck_id: truck4.id, user_id: priyam.id, content:"Hello cheese!!! Who doesn't love cheese?! I duno why the star rating is so low, my sandwich was nothing short of stupendous! I got the today's melt with a drink & tots for $9, steal! Today's melt was: muenster, bacon (good quality bacon & they didn't skimp on it), jalapeños & chipotle sauce on white. Everything was excellent! My sandwich was melted perfectly, there were plenty of jalapeños, lots of juicy bacon, & not too much sauce to mask any flavor. The tots were also awesome. The gentleman cooks were all very kind & flashed me lots of smiles. I had a very short wait & I was off to enjoy this cheesy goodness!")
review10 = Review.create(title: "Great Place",  rating: 5, truck_id: truck5.id, user_id: frankie.id, content:"Vegan food which vegans and carnivores can both enjoy :D The beast mode burger on greens with red quinoa was ridic tasty. My friend had the smoked sage seitan burger over greens...Can't wait to eat here again!")
# review11(title: ,  rating: , truck_id: , user_id: , content:)
# review12(title: ,  rating: , truck_id: , user_id: , content:)
# review13(title: ,  rating: , truck_id: , user_id: , content:)
# review14(title: ,  rating: , truck_id: , user_id: , content:)
# review15(title: ,  rating: , truck_id: , user_id: , content:)
# review16(title: ,  rating: , truck_id: , user_id: , content:)
# review17(title: ,  rating: , truck_id: , user_id: , content:)
# review18(title: ,  rating: , truck_id: , user_id: , content:)
# review19(title: ,  rating: , truck_id: , user_id: , content:)
# review20(title: ,  rating: , truck_id: , user_id: , content:)
# review21(title: ,  rating: , truck_id: , user_id: , content:)
# review22(title: ,  rating: , truck_id: , user_id: , content:)
# review23(title: ,  rating: , truck_id: , user_id: , content:)
# review24(title: ,  rating: , truck_id: , user_id: , content:)
# review25(title: ,  rating: , truck_id: , user_id: , content:)

item1 = Item.create(name:"Beef Over Rice", price: 11, truck_id: truck1.id )
item2 = Item.create(name:"Chicken and Beef Combo over Rice", price: 12, truck_id: truck1.id )
item3 = Item.create(name:"Chicken over Rice", price: 9, truck_id: truck1.id )
item4 = Item.create(name:"Chicken and Beef Combo Sandwich", price: 10, truck_id: truck1.id )
item5 = Item.create(name:"Chicken Sandwich", price: 9, truck_id: truck1.id )
item6 = Item.create(name:"Gyro Sandwich", price: 10, truck_id: truck1.id )
item7 = Item.create(name:"Falafel Sandwich", price: 6, truck_id: truck1.id )
item8 = Item.create(name:"Falafel over Rice", price:6, truck_id: truck1.id )

item9 = Item.create(name:"Feta Salad", price:13, truck_id: truck2.id )
item10 = Item.create(name:"Kale Salad with Tempeh", price:13, truck_id: truck2.id )
item10 = Item.create(name:"Quinoa Salad", price:12, truck_id: truck2.id )
item11 = Item.create(name:"Tuna Salad", price: 13, truck_id: truck2.id )
item12 = Item.create(name:"Sweet Spin", price:8, truck_id: truck2.id )
item13 = Item.create(name:"Xtreme Greens", price:8, truck_id: truck2.id )
item14 = Item.create(name:"Chia Berry", price:8, truck_id: truck2.id )
item15 = Item.create(name:"PB Power", price:10, truck_id: truck2.id )
item15 = Item.create(name:"Coconut Water", price:6, truck_id: truck2.id )

# Wafels and Dinges
item16 = Item.create(name:"The Brussels Wafel", price:12, truck_id: truck3.id )
item17 = Item.create(name:"lÃ¨ge wafel", price:12, truck_id: truck3.id )
item18 = Item.create(name:"Mini Wafelini", price:12, truck_id: truck3.id )
item19 = Item.create(name:"de Throwdown wafel", price: 12, truck_id: truck3.id )
item20 = Item.create(name:"Ice Cream Wafel Cone", price:14, truck_id: truck3.id )
item21 = Item.create(name:"BBQ Pulled Pork Wafel", price:13, truck_id: truck3.id )
item22 = Item.create(name:"de bacon + syrup wafel", price:15, truck_id: truck3.id)
item23 = Item.create(name:"chilli con corne", price:10, truck_id: truck3.id )
item24 = Item.create(name:"LiÃ¨ge Wafel", price:11, truck_id: truck3.id )
item25 = Item.create(name:"hot belgian cocoa", price:5, truck_id: truck3.id )
item26 = Item.create(name:"Cold Brew Coffee", price:4, truck_id: truck3.id )
item27 = Item.create(name:"Tea", price:3, truck_id: truck3.id )
item28 = Item.create(name:"Coffee", price:3, truck_id: truck3.id )

# Gorilla Cheese
item29 = Item.create(name:"Build Your Own Sandwich", price:11, truck_id: truck4.id )
item30 = Item.create(name:"#4", price:10, truck_id: truck4.id )
item31 = Item.create(name:"#5", price:10, truck_id: truck4.id )
item32 = Item.create(name:"#6", price: 10, truck_id: truck4.id )
item33 = Item.create(name:"#7", price: 10, truck_id: truck4.id )
item34 = Item.create(name:"#8", price: 10, truck_id: truck4.id )
item35 = Item.create(name:"#9", price: 10, truck_id: truck4.id )
item36 = Item.create(name:"#10", price:10, truck_id: truck4.id )
item37 = Item.create(name:"#11", price:10, truck_id: truck4.id )
item38 = Item.create(name:"#12", price:10, truck_id: truck4.id )
item39 = Item.create(name:"#14", price:10, truck_id: truck4.id )
item40 = Item.create(name:"Tots with Cheese & Bacon", price:9, truck_id: truck4.id )
item41 = Item.create(name:"Mac & Cheese Bites", price:8, truck_id: truck4.id )
item42 = Item.create(name:"Tomato Soup", price:7, truck_id: truck4.id )
item43 = Item.create(name:"Tomato Soup Shooter", price:8, truck_id: truck4.id )
item44 = Item.create(name:"Tater Tots", price:8, truck_id: truck4.id )

# Cinnamon Snail -- vegan
item45 = Item.create(name:"Thai BBQ Tempeh", price:12, truck_id: truck5.id )
item46 = Item.create(name:"Thanksgiving Sandoo", price:12.5, truck_id: truck5.id )
item47 = Item.create(name:"Maple Mustard Tempeh Sandwich", price:10.75, truck_id: truck5.id )
item48 = Item.create(name:"Korean Barbeque Seitan", price: 11.25, truck_id: truck5.id )
item49 = Item.create(name:"Beastmode Burger Deluxe", price: 12, truck_id: truck5.id )
item50 = Item.create(name:"Tamarind Plum Glazed Lentil Burger", price: 12, truck_id: truck5.id )
item51 = Item.create(name:"Smoked Sage Seitan Burger", price: 12, truck_id: truck5.id )
item52 = Item.create(name:"House Salad", price:12, truck_id: truck5.id )
item53 = Item.create(name:"Rosemary Sunflower Crusted Tofu", price:16.5, truck_id: truck5.id )
item54 = Item.create(name:"French Mustard Grilled Seitan", price:15.5, truck_id: truck5.id )
item55 = Item.create(name:"Creamy Mashed Potatoes", price:5.75, truck_id: truck5.id )
item56 = Item.create(name:"Baked Ziti", price:6, truck_id: truck5.id )
item57 = Item.create(name:"Kimchi Tater Tots ", price:6, truck_id: truck5.id )
item58 = Item.create(name:"Baked Cashew Cheese Tater Tots", price:6.5, truck_id: truck5.id )
item59 = Item.create(name:"Jalapeno Mac N Cheese", price:5.5, truck_id: truck5.id )
item60 = Item.create(name:"Red Quinoa Pilaf ", price:6, truck_id: truck5.id )

# Luke's Lobster
item61 = Item.create(name:"lobster Roll", price:18, truck_id: truck6.id )
item62 = Item.create(name:"Crab Roll", price:13, truck_id: truck6.id )
item63 = Item.create(name:"Shrimp Roll", price:9, truck_id: truck6.id )
item64 = Item.create(name:"Luke's Trio", price: 20, truck_id: truck6.id )
item65 = Item.create(name:"Lobster Mac & Cheese", price: 15, truck_id: truck6.id )
item66 = Item.create(name:"Bread Bowl", price: 12, truck_id: truck6.id )
item67 = Item.create(name:"Wild Blue Salad", price:15, truck_id: truck6.id )
item68 = Item.create(name:"Lobster & Gruyere Grilled Cheese.", price:13, truck_id: truck6.id )
item69 = Item.create(name:"Crab & Gruyere Grilled Cheese.", price:10, truck_id: truck6.id )
item70 = Item.create(name:"Clam Chowder", price: 6, truck_id: truck6.id )
item71 = Item.create(name:"Lobster Bisque", price:7, truck_id: truck6.id )
item72 = Item.create(name:"Cape Cod Chips", price:2, truck_id: truck6.id )
item73 = Item.create(name:"Poppy Seed Slaw", price:2, truck_id: truck6.id )
#
# Kimchi Taco
item74 = Item.create(name:"Kimchi Taco", price:4, truck_id: truck7.id )
item75 = Item.create(name:"Big Belly Burrito", price:9.75, truck_id: truck7.id )
item76 = Item.create(name:"Fresh Kimchi Bowl", price: 9.75, truck_id: truck7.id )
item77 = Item.create(name:"Spicy Korean Rice Gnocchi", price: 4.75, truck_id: truck7.id )
item78 = Item.create(name:"Kimchi Arancini", price:5.75, truck_id: truck7.id )
item79 = Item.create(name:"BBQ Nachos", price:6.75, truck_id: truck7.id )
item80 = Item.create(name:"Kimchi Fries", price: 6, truck_id: truck7.id )


# # Souvlaki GR
item81 = Item.create(name:"Hummus ", price:6, truck_id: truck8.id )
item82 = Item.create(name:"Eggplant", price:6, truck_id: truck8.id )
item83 = Item.create(name:"Spicy Feta", price: 6, truck_id: truck8.id )
item84 = Item.create(name:"Tzatziki", price: 6, truck_id: truck8.id )
item85 = Item.create(name:"Pork Skewer", price: 3.5, truck_id: truck8.id )
item86 = Item.create(name:"Chicken Skewer", price:3.5, truck_id: truck8.id )
item87 = Item.create(name:"Pork Pita", price: 6, truck_id: truck8.id )
item88 = Item.create(name:"Bifteki (Greek Burger) Pita", price: 7, truck_id: truck8.id )
item89 = Item.create(name:"Shrimp Pita", price: 7, truck_id: truck8.id )
item90 = Item.create(name:"Traditional Greek Salad", price: 9, truck_id: truck8.id )
item91 = Item.create(name:"Hand Cut Fries", price: 5, truck_id: truck8.id )
item92 = Item.create(name:"Hand Cut Greek Fries", price: 6, truck_id: truck8.id )

# Toum NYC
item93 = Item.create(name:"Tabouleh Salad", price:5, truck_id: truck9.id )
item94 = Item.create(name:"Babaghanouj", price:6, truck_id: truck9.id )
item95 = Item.create(name:"Chicken Shawarma Sandwich", price: 8, truck_id: truck9.id )
item96 = Item.create(name:"Chicken Shawarma Platter", price: 11, truck_id: truck9.id )
item97 = Item.create(name:"Beef Kabab Sandwich", price: 8.5, truck_id: truck9.id )
item98 = Item.create(name:"Beef Kabab Platter", price:11.5, truck_id: truck9.id )
item99 = Item.create(name:"Makanek Sandwich", price: 8, truck_id: truck9.id )
item100 = Item.create(name:"Makanek Platter", price: 11, truck_id: truck9.id )
item101 = Item.create(name:"Grilled Kafta Sandwich", price: 8.5, truck_id: truck9.id )
item102 = Item.create(name:"Fried Kibbeh", price: 2.5, truck_id: truck9.id )
item103 = Item.create(name:"Lahem B'ajeen", price: 4, truck_id: truck9.id )
item104 = Item.create(name:"Spinach Pie", price: 2, truck_id: truck9.id )
item105 = Item.create(name:"Grape Leaves", price: 6, truck_id: truck9.id )
item106 = Item.create(name:"Grilled Halloumi Sandwich", price: 8, truck_id: truck9.id )
item107 = Item.create(name:"Falafel Sandwich", price: 6, truck_id: truck9.id )
item108 = Item.create(name:"Falafel Platter", price: 9, truck_id: truck9.id )
item109 = Item.create(name:"Vegetarian Platter", price: 9, truck_id: truck9.id )

# Korilla BBQ
item110 = Item.create(name:"Spicy Pork Noodle Bowl", price:9.5, truck_id: truck10.id )
item111 = Item.create(name:"Bulgogi Rice Bowl", price:10, truck_id: truck10.id )
item112 = Item.create(name:"Hot Chix Rice Bowl", price: 9.5, truck_id: truck10.id )
item113 = Item.create(name:"Spicy Pork Rice Bowl", price: 9.5, truck_id: truck10.id )
item114 = Item.create(name:"Tofu Rice Bowl", price: 9.5, truck_id: truck10.id )
item115 = Item.create(name:"Bulgogi Salad", price:9.5, truck_id: truck10.id )
item116 = Item.create(name:"Makanek Sandwich", price: 10, truck_id: truck10.id )
item117 = Item.create(name:"Spicy Pork Salad", price: 9.5, truck_id: truck10.id )
item118 = Item.create(name:"Hot Chix Salad", price: 9.5, truck_id: truck10.id )
item119 = Item.create(name:"Tiger Balls", price: 4, truck_id: truck10.id )

# Coney Foodtruck
item120 = Item.create(name:"Casadia Chicken Beef Or Pork", price:5, truck_id: truck11.id )
item121 = Item.create(name:"Grill Cheese Chicken, Beef Or Pork", price: 4, truck_id: truck11.id )
item122 = Item.create(name:"Tripple Grill Cheese", price: 4, truck_id: truck11.id )
item123 = Item.create(name:"Hot Dogs", price: 2.5, truck_id: truck11.id )
item124 = Item.create(name:"Tacos", price: 7, truck_id: truck11.id )
